const defaults = {
  maxTitleWidth: 9,
  maxTitleLines: 4,
  ratingStep: 0.5,
  volumeStep: 10,
  volume: 100,
  seekStep: 10,
  playlistName: "",
  startPlayback: true,
  shufflePlaylist: false,
  playerShuffleOnPlaylist: "Off",
  sortByAlbum: false,
  playlistPosition: "Clear",
  useCurrentTrack: true,
  trackTitle: "",
  album: "",
  artist: "",
}
